name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present

      - name: unit test
        run: npm run test:cov
        continue-on-error: false

      - name: upload coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage/lcov-report/index.html
      
#       - name: e2e
#         run: npm run test:e2e
#         continue-on-error: false
        
        env:
          CI: true
